# Generated by Django 5.1.2 on 2024-12-09 15:20

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('#000000', 'Black'), ('#FFFFFF', 'White'), ('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue')], max_length=39),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=8),
        ),
    ]
