# Generated by Django 5.1.2 on 2025-01-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_photo'),
    ]

    operations = [
        
    ]
